import 'package:drift/drift.dart';
import 'package:uuid/uuid.dart';
import '../../../core/database/database.dart';
import '../../../core/database/daos/transaction_dao.dart';

class RecurringService {
  final TransactionDao _transactionDao;

  RecurringService(this._transactionDao);

  Future<void> evaluateRecurringExpenses() async {
    final templates = await _transactionDao.getRecurringTransactions();
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);

    for (final template in templates) {
      if (template.recurrenceType == null) continue;

      // Determine next occurrence date based on the latest generated occurrence
      // If we don't have a robust way to find the latest occurrence generated by this template,
      // we'll rely on the transaction_date of the template itself as the starting point.
      // Wait, if the template is an actual transaction (e.g. they paid it today),
      // then we should look for transactions with the same category, amount, currency,
      // and note (we'll append a marker to the note when generating).
      
      // Let's find all instances that were generated from this template
      // We can use a special format in the note field: " [recurring: {templateId}]"
      final instances = await (_transactionDao.select(_transactionDao.transactions)
            ..where((t) => t.isRecurring.equals(false))
            ..where((t) => t.note.like('%[recurring: ${template.id}]%'))
            ..where((t) => t.deletedAt.isNull())
            ..orderBy([(t) => OrderingTerm.desc(t.transactionDate)]))
          .get();

      DateTime lastDate = template.transactionDate;
      if (instances.isNotEmpty) {
        lastDate = instances.first.transactionDate;
      }
      lastDate = DateTime(lastDate.year, lastDate.month, lastDate.day);

      // Generate missing periods up to today
      while (true) {
        DateTime nextDate;
        switch (template.recurrenceType) {
          case 'weekly':
            nextDate = lastDate.add(const Duration(days: 7));
            break;
          case 'fortnightly':
            nextDate = lastDate.add(const Duration(days: 14));
            break;
          case 'monthly':
            nextDate = DateTime(lastDate.year, lastDate.month + 1, lastDate.day);
            break;
          default:
            nextDate = lastDate.add(const Duration(days: 36500)); // break out
        }

        if (nextDate.isAfter(today)) {
          break; // Next occurrence is in the future
        }

        // Generate the transaction
        final newId = const Uuid().v4();
        
        // Append recurring marker to note if not already there
        String baseNote = template.note ?? '';
        // If template already has a marker (shouldn't happen on true template), clean it
        if (baseNote.contains('[recurring:')) {
          baseNote = baseNote.split('[recurring:').first.trim();
        }
        
        final instanceNote = '$baseNote [recurring: ${template.id}]'.trim();

        final companion = TransactionsCompanion(
          id: Value(newId),
          transactionType: Value(template.transactionType),
          amountBase: Value(template.amountBase),
          originalAmount: Value(template.originalAmount),
          originalCurrency: Value(template.originalCurrency),
          exchangeRate: Value(template.exchangeRate),
          rateDate: Value(template.rateDate),
          rateEstimated: Value(template.rateEstimated),
          rateSource: Value(template.rateSource),
          categoryId: Value(template.categoryId),
          note: Value(instanceNote),
          transactionDate: Value(nextDate),
          isRecurring: const Value(false),
          recurrenceType: const Value(null),
          syncStatus: const Value('pending'),
          createdAt: Value(DateTime.now()),
          updatedAt: Value(DateTime.now()),
        );

        await _transactionDao.insertTransaction(companion);
        
        // Update lastDate for next iteration
        lastDate = nextDate;
      }
    }
  }
}
